<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyVersion>1.1</AssemblyVersion>
    <FileVersion>1.1</FileVersion>
    <Title>Shared</Title>
    <Version>1.1</Version>
    <Authors>Pieter Witvoet</Authors>
    <Company></Company>
    <Product>Shared</Product>
    <Description></Description>
    <Copyright>Copyright © Pieter Witvoet 2021</Copyright>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.11" />
    <PackageReference Include="System.Formats.Nrbf" Version="10.0.7" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Properties\" />
  </ItemGroup>

</Project>
